import Dashboard from '@/components/Dashboard';
import Head from 'next/head';
import { useUser } from '@auth0/nextjs-auth0/client';
import Login from '@/components/Login';

export default function Home() {
  const { user } = useUser();
  return (
    <>
      <Head>
        <title>GitHub Analyzer</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {user ? <Dashboard /> : <Login />}
    </>
  );
}
